"""empty message

Revision ID: 2a09d69f90d5
Revises: f8eb440dddd5
Create Date: 2022-06-17 12:05:16.454238

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2a09d69f90d5'
down_revision = 'f8eb440dddd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books_genres', sa.Column('genre_id', sa.Integer(), nullable=False))
    op.drop_constraint('fk_books_genres_user_id_users', 'books_genres', type_='foreignkey')
    op.create_foreign_key(op.f('fk_books_genres_genre_id_genres'), 'books_genres', 'genres', ['genre_id'], ['id'])
    op.drop_column('books_genres', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books_genres', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_books_genres_genre_id_genres'), 'books_genres', type_='foreignkey')
    op.create_foreign_key('fk_books_genres_user_id_users', 'books_genres', 'users', ['user_id'], ['id'])
    op.drop_column('books_genres', 'genre_id')
    # ### end Alembic commands ###
