"""empty message

Revision ID: 6d7164d4a947
Revises: e67334693e01
Create Date: 2022-06-20 18:54:15.115876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d7164d4a947'
down_revision = 'e67334693e01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reviews_status')),
    sa.UniqueConstraint('status', name=op.f('uq_reviews_status_status'))
    )
    op.add_column('reviews', sa.Column('review_status_id', sa.Integer(), nullable=False))
    op.create_foreign_key(op.f('fk_reviews_review_status_id_reviews_status'), 'reviews', 'reviews_status', ['review_status_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_reviews_review_status_id_reviews_status'), 'reviews', type_='foreignkey')
    op.drop_column('reviews', 'review_status_id')
    op.drop_table('reviews_status')
    # ### end Alembic commands ###
